version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    command: npm start